### ISSUE TITLE
Two of the pdf links in the readme are dead

### ISSUE THREAD

**Issue by msm-code** [holdenlee/number-theory#4]
By the way, I just noticed two out of three book links are broken:

Analytic number theory: [tiny.cc/annt](http://tiny.cc/annt)
Number theory: [tiny.cc/ntbook](http://tiny.cc/ntbook)

I don't remember this being a case a week and a month ago, but it's possible I just downloaded a pdf file from repository.

I can host these files and send a PR with a working location, but I assume you prefer to keep hosting them yourself instead of trusting a random new contributor.

**Comment by holdenlee** [comment]
Just fixed.
